### ISSUE TITLE
Displays wrong Cardano token price for Drip

### ISSUE THREAD

**Issue by Zerophase** [LedgerHQ/ledger-live#1272]
**Describe the bug**

Ledger Live grabs the wrong price feed for Drip. The governance token for Drip Dropz, the Cardano token distributor. 

**To Reproduce**

1. Check value of portfolio.
2. Buy some Drip or get it through their site.
3. Notice value of portfolio substantially increases, far more than the amount bought or distributed.

**Expected behavior**

Value of portfolio approximately matches the amount of Drip bought with slight variability. Not a few thousand percent increase.

**Comment by haammar-ledger** [comment]
Hi @Zerophase thanks for reporting the issue.
To clarify, are you referring to the value in Drip currency, or the countervalue in fiat?

**Comment by gre** [comment]
please prefer to go through our Customer Support to investigate this problem more quickly with you
https://support.ledger.com/

Thanks

**Comment by wickles** [comment]
@gre Please work with us to resolve the issue here. If this is not the place for Ledger Live bug reports then please direct us to the appropriate issue tracker. 

For me, DRIP and MYST tokens on Cardano have the wrong price and seriously mess with my whole portfolio value. Hiding these tokens temporarily suppresses them but they reappear after closing and opening Ledger Live again, even though they are still in the "Hidden tokens" for Cardano under account settings.
