### ISSUE TITLE
sha512sum hash verification non-functional

### ISSUE THREAD

**Issue by acashmoney** [LedgerHQ/ledger-live#251]
**Describe the bug**

Can not confirm on Mac (and potentially other OS) that sha512 hashes published in `ledger-live-desktop-2.42.0.sha512sum` are signed by Ledger.

**To Reproduce**

1. Visit [Verification Instructions](https://live.ledger.tools/lld-signatures)
2. Click download links for `ledger-live-desktop-2.42.0-mac.dmg`, `ledger-live-desktop-2.42.0.sha512sum`, `ledgerlive.pem`
3. Follow instructions for **Verify the sha512sum hashes**

**Expected behavior**

Downloaded files
```
ledger-live-desktop-2.42.0-mac.dmg
ledgerlive.cer
ledger-live-desktop-2.42.0.sha512sum.sig
```
Instructions indicate sha256 verification when it should be sha512. Updating the command syntax to sha512 and the downloaded files produces `Verification Failure`

**Screenshots**

![Verification Failure](https://i.postimg.cc/Y0YtxZQk/Screen-Shot-2022-06-03-at-2-13-36-AM.png)

**Desktop (please complete the following information):**
 - macOS Monterey 12.4

**Additional context**

It appears the Ledger Live verification instructions need to be updated and/or the sha512 hashes are not being signed by Ledger.

**Comment by acashmoney** [comment]
**UPDATE**

Please see below for the correct files to compare according to the instructions and same Verification Failure.

*Downloaded files*
```
ledger-live-desktop-2.42.0-mac.dmg
ledger-live-desktop-2.42.0.sha512sum
ledger-live-desktop-2.42.0.sha512sum.sig
ledgerlive.cer
```

*Screenshot*

<img width="568" alt="Screen Shot 2022-06-03 at 10 35 57 AM" src="https://user-images.githubusercontent.com/29086101/171819525-f0981332-c014-45af-8200-379102e427b3.png">

*vs. Ledger Live [instructions](https://live.ledger.tools/lld-signatures)*

```
$ openssl dgst -sha256 -verify ledgerlive.pem -signature ledger-live-desktop-2.42.0.sha512sum.sig ledger-live-desktop-2.42.0.sha512sum

Verified OK
```
*Differences*

- sha512 instead of sha256
- .cer instead of .pem certificate

**Comment by gre** [comment]
@acashmoney  I just went through the instructions of https://www.ledger.com/ledger-live/lld-signatures

and to me it works correctly:

<img width="570" alt="Screenshot 2022-06-06 at 15 53 32" src="https://user-images.githubusercontent.com/211411/172174694-ff3f37ec-2756-4e84-89e0-3ed9adc0d803.png">

- The installer binaries are all hashed using SHA512 into a checksum files:
```
$ cat ledger-live-desktop-2.42.0.sha512sum
51d61df7e9c0c716eaa57700dc871e745d2206727c3400b06ef6c30a0e535679ee99bb2f04dbafdbcdcc5e28dc24f97e6fb5c811360a5df83ace517651c192dc ledger-live-desktop-2.42.0-linux-x86_64.AppImage
dfea05c59003b60a55a50998285c4f57b261b09fd211cc0e624cbfa82690be069abcebb0e07e12a61634deb28035a5bf49557a2afdb12fc5306e2743b915cbb8 ledger-live-desktop-2.42.0-mac.dmg
ef20a9edb9f5419db1379e756f170faed0a7dd6893aa961df47d76970b09f6fc0448b89e7f934127f265f5ae4da72d3852b3815005dc00883d82f8c69f42ad49 ledger-live-desktop-2.42.0-mac.zip
0fb189e8e6f3f6d15a298040ccc896d43f09766b25f7fba67d549fe09ec14269d41bead677186ed2acfa2ce458a78c37481307c3fe7599d80688a10f320ff563 ledger-live-desktop-2.42.0-win-x64.exe
```
- a SHA256 hash of this file is then produced. in this case, `c0bf4150fa081dba51b42997df59c913f1440f7bc9086fefff303abc55d4c3c3`
- a signature of this hash is done by ledger. it's the .sig file.

that's why you give `-sha256` to openssl as it need to hash with SHA256 the ledger-live-desktop-2.42.0.sha512sum checksum file.

Indeed we use a combination of SHA 512 and SHA 256 and this probably creates this confusion. I hope this explanation makes sense.

**Comment by acashmoney** [comment]
Thanks for clearing up the confusion @gre. Verification works now on my end. Cheers!
