### ISSUE TITLE
Tagging releases for external consumers

### ISSUE THREAD

**Issue by andresilva** [LedgerHQ/ledger-live#397]
**Context**

Ledger Live Desktop

**Is your feature request related to a problem? Please describe.**

 
I am the maintainer of the ledger-live-desktop package for NixOS. Before the change to the monorepo the https://github.com/LedgerHQ/ledger-live-desktop repo was using the releases feature to tag the latest releases. This was very useful to me as I could watch the repo for new releases and get notified about it. There doesn't seem to be any tagging of new releases as of now. I just looked at the `main` branch and it seems like this is where releases get cut. It also doesn't seem like the release artifacts are published on GitHub anymore, should I just download them from the ledger website?

**Describe the solution you'd like**

Start using GitHub releases again.

**Describe alternatives you've considered**

Any alternative that allows me to subscribe to that specific event on GitHub.

**Comment by valpinkman** [comment]
Hello @andresilva 

Since we just migrated to a monorepo, some process/flows were not all properly setup, but the next releases for Desktop and Mobile will (should) be tagged. 

However, it was not a developer choice to host the binaries somewhere else than Github, and that, we cannot have a say in this for legal reasons. 

Also yes, Ledger website is the place to go if you need to download the latest version of Ledger Live Desktop (Mobile always go through Apple and Google Stores anyway)

As we moved to a monorepository architecture, we are not sure yet we still want to use github releases (independent of the fact that the binaries will not be attached to that release), but we'll think about it.

Thank you for the feedback 

closing now as there is no actions to take for now
