### ISSUE TITLE
Ledger Live desktop application doesn't recognize the dongle when dongle is connected via bluetooth with mobile app

### ISSUE THREAD

**Issue by cpuell** [LedgerHQ/ledger-live#480]
**Describe the bug**

The dongle is connected via bluetooth to the mobile app and when opening the desktop app and trying to open the "Manager" section, it doesn't recognize the dongle. Normally the dongle would require you to confirm the opening of the manager section, but right now, it doesn't.

Each of the steps provided in the first level troubleshoot doesn't work, neither the reset of the device. I tried the reboot of the computer, different usb port, disconnect and reconnect the dongle when Live Ledger app is open and closed.

**To Reproduce**

1. Go to dongle and enable bluetooth
2. Go to mobile app and connect dongle with live ledger app
3. Go to desktop app and try to open the manager section
4. See that the app is trying to wait for the device, but nothing happens
5. Go to mobile app
6. Open "My ledger" section
7. Select device from list
8. App is asking to keep the device near the dongle
9. Go to dongle and it request confirmation to open the manager section
10. Confirm the request at the dongle
11. Go to app and see the manager section is opened

Above steps shows, that the mobile app is working fine connecting with the dongle, but the desktop app cannot connect.

**Expected behavior**

The desktop app should recognize the dongle even it is already connected via bluetooth with the mobile device.

**Desktop (please complete the following information):**
 - OS: Monterey 12.4

**Smartphone (please complete the following information):**
 - Device: iPhone 12 pro
 - OS: OS15.5
 - Live Ledger Mobile app: 3.2.0 (383)
 - Live Ledger version: V2.0.2

**Additional context**

_Add any other context about the problem here._

**Comment by juan-cortes** [comment]
@cpuell as of today you are correct in your assessment. We can't connect to a device with multiple _transports_. In this case, BLE and USB transports. Ledger Live desktop will be able to see the device but not communicate with it, since the device will not respond while connected via BLE.

There are some changes incoming that will release the BLE connection after an interaction and this will allow the USB side to talk again with the nano. This will probably feel more natural from a user perspective. I will leave a note to ping back on this thread once we release that version so you're the first to know. In the meantime, I'm closing the issue.
