### ISSUE TITLE
Expedite review of broken Nano X apps

### ISSUE THREAD

**Issue by wickles** [LedgerHQ/ledger-live#617]
Cosmos and Centrifuge apps have recently been updated to resolve issues preventing some users from accessing funds, yet the updated apps are still not available on Ledger Live. Since Nano X users have no way to sideload in order to access their funds, the review process for these updates should be prioritized. 

https://github.com/Zondax/ledger-centrifuge/issues/35
https://github.com/cosmos/ledger-cosmos/issues/65
https://github.com/cosmos/ledger-cosmos/issues/66

**Comment by gre** [comment]
I will forward the information internally but this is not something to fix in "Ledger Live" itself, but more in the ledger nano app store api. thanks

**Comment by FabriceDautriat** [comment]
Sorry @wickles , but indeed opening the issue here will not help. It will be better addressed [here](https://github.com/LedgerHQ/app-cosmos)

Please also read https://developers.ledger.com/docs/nano-app/submission-form/
We review Nano app updates after the developer/owner of the application actually pushes a PR an fills this form.

https://github.com/Zondax/ledger-centrifuge/issues/35 ==> Indeed Ledger didn't release any updates yet. The last version is 2.34.4. We'll look into a possible PR made by Zondax or ICF to [our repor](https://github.com/LedgerHQ/app-cosmos) to cover this. So far I haven't found one... (cc @tjulien-ledger )

https://github.com/cosmos/ledger-cosmos/issues/65 ==>  Apparently it's solved [here](https://github.com/cosmos/ledger-cosmos/releases/tag/v2.34.5). We need to receive a PR to [our repo](https://github.com/LedgerHQ/app-cosmos) to be able to merge the fix. (cc @tjulien-ledger )

In any case, we are going to address this issue asap and contact the Zondax / ICF to discuss this further and avoid this situation happens again.

**Comment by FabriceDautriat** [comment]
The new version 2.34.6 was released yesterday. Please give it a try @wickles !

**Comment by wickles** [comment]
Solved my problem for Cosmos, thanks! Any news for Centrifuge?

**Comment by wickles** [comment]
> With respect to Centrifuge, the chain went through backwards incompatible changes. Unfortunately, Zondax does not have any maintenance agreement with them. As an alternative, we have offered building a light app under an agreement we have with the web3 foundation. This light app could/should be submitted by the Centrifuge team.

That is interesting. In the Centrifuge issue that I linked they suggested that the latest (unverified) version should support the parachain. 

> Hi! There's a new release (v1.1005.0) that support Centrifuge parachain balances pallet. As LNX doesn't support unofficial app sideloading (aka you can only install apps in Ledger Live) this app version is, for the moment, only available for NanoS and NanoSP using our installers, found in the latest release.

I got hold of a Nano SP just to test this out and it doesn't work.
