### ISSUE TITLE
Remove node-usb-detection dependency

### ISSUE THREAD

**Issue by sagotch** [LedgerHQ/ledger-live#876]
**Context**

[@ledgerhq/hw-transport-node-hid-singleton](https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledgerjs/packages/hw-transport-node-hid-singleton)

**Is your feature request related to a problem? Please describe.**

`node-usb-detection` dependency make [@ledgerhq/hw-transport-node-hid-singleton](https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledgerjs/packages/hw-transport-node-hid-singleton) unavailable for Electron14+. Electron version below 18 are not supported anymore.

[node-usb-detection](https://github.com/MadLittleMods/node-usb-detection/pull/169) will be deprecated soon anyway.

**Describe the solution you'd like**

Move to `node-usb` which provides a small [guide](https://github.com/node-usb/node-usb#migrating-from-node-usb-detection) to help making the transition.

I tried to look at it, but I do not have competencies to make the changes my self.

Thanks.

---

EDIT: related PR -> https://github.com/LedgerHQ/ledger-live/pull/903

**Comment by gre** [comment]
> https://github.com/MadLittleMods/node-usb-detection/pull/169 will be deprecated soon anyway.

wow indeed! Thanks for raising this to us. We will have to give a try to `node-usb` but I know this library was problematic to us in the past, I can't find again the reason unfortunately. It was back in 2018, so it might have improved since then.

The only annoying part is the fact we already have `node-hid` and unfortunately miss only one feature that we need: the ability to detect a device was plugged or unplugged, in order to slightly improve the performance and the UX: being able to know when a device is plugged then allow us to only do one node-hid `open()` at the best time, action which is quite costly and wouldn't be good to "poll".

I guess no choice to first give a try to node-usb and assess it works in all our environments.

**Comment by gre** [comment]
https://ledgerhq.atlassian.net/browse/LIVE-3247

**Comment by juan-cortes** [comment]
I'm on it

**Comment by sagotch** [comment]
Fixed in latest release. Thanks!
